baseURL = 'https://riveck.com/'
languageCode = 'en-us'
title = 'Ricard Flores - The Happy CISO'
theme = 'PaperMod'
enableEmoji = true
paginate = 5
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

